project:
  version: "0.0.1-SNAPSHOT"
validation:
  enabled: true

app:
  cors:
    allowedOrigins: https://gothmog.ru, it-gothmog.ru, https://ingress.gothmog.ru, ingress.it-gothmog.ru, http://127.0.0.1:${SERVER_PORT:8080}
    allowCredentials: true
  openapi:
    local-url: http://127.0.0.1:${SERVER_PORT:8080}
    develop-url: https://ingress.dev-gothmog.ru
    ift-url: https://ingress.ift-gothmog.ru
    prod-url: https://ingress.gothmog.ru

logging:
  level:
    root: INFO
    ru: info
    web: DEBUG
    org:
      hibernate:
        SQL: info
    com:
      zaxxer:
        hikari:
          HikariConfig: INFO


management:
  endpoints:
    web:
      base-path: /api/v1
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true

spring:
  application:
    name: ${APP_SERVER_NAME:employs-ws-app}
  profiles:
    active: local
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jmx:
    enabled: false
  liquibase:
    contexts: ${spring.profiles.active}
    enabled: true
  main:
    banner-mode: 'off'

springdoc:
  api-docs:
    path: /api-docs
  cache:
    disabled: true
  swagger-ui:
    config-url: /api-docs/swagger-config
    disable-swagger-default-url: true
    path: /swagger-ui.html
    url: /api-docs
    use-root-path: true
